Homepage/Models/ErrorViewModel.cs
namespace Homepage.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Homepage/Controllers/DownloadController.cs
using System.Net.Mime;
using Microsoft.AspNetCore.Mvc;

namespace Homepage.Controllers;

public class DownloadController : Controller
{
    public IActionResult Index(string filename)
    {
        var file = $"./wwwroot/download/{filename}";
        if (!System.IO.File.Exists(file))
            return NotFound();
        
        var bytes = System.IO.File.ReadAllBytes(file);
        System.IO.File.Delete(file);
        
        var cd = new ContentDisposition
        {
            FileName = filename,
            Inline = false
        };
        Response.Headers.Add("Content-Disposition", cd.ToString());
        Response.Headers.Add("X-Content-Type-Options", "nosniff");
        return File(bytes, "application/octet-stream");
    }
}

Homepage/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Homepage.Models;

namespace Homepage.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Homepage/Controllers/ToolsController.cs
using Homepage.Util;
using Microsoft.AspNetCore.Mvc;

namespace Homepage.Controllers;

public class ToolsController : Controller
{
    private readonly ILogger<ToolsController> _logger;
    private readonly HomebankConverter _homebankConverter;
    private readonly FileManager _fileManager;

    #region Constructor

    public ToolsController(
        HomebankConverter homebankConverter,
        ILogger<ToolsController> logger,
        FileManager fileManager)
    {
        _homebankConverter = homebankConverter;
        _logger = logger;
        _fileManager = fileManager;
    }

    #endregion

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult HomebankConvert()
    {
        try
        {
            var file = Request.Form.Files.FirstOrDefault();
            if (file == null || file.Length == 0)
                return BadRequest();

            using var ms = new MemoryStream();
            file.CopyTo(ms);
            var result = _homebankConverter.Convert(ms.ToArray());
            var filename = $"{Path.GetFileNameWithoutExtension(file.FileName)}-homebank.csv";
            _fileManager.WriteForDownload(result, filename);
            Response.Headers.Add(Htmx.HtmxResponseHeaders.Keys.Redirect, $"/download/{filename}");
            return Ok();
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Error while converting Homebank file");
            return StatusCode(500);
        }
    }
}

Homepage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "LUXICK.DE";
    ViewData["SUbTitle"] = "Personal Website";
}

<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

Homepage/Views/Shared/_Layout.cshtml
@using Htmx.TagHelpers
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="htmx-config"
          historyCacheSize="20"
          indicatorClass="htmx-indicator"
          includeAspNetAntiforgeryToken="true"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/classless.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body hx-boost="true">
<header>
    <section>
        <h1>@ViewData["Title"]</h1>
        <p><strong>@ViewData["SubTitle"]</strong></p>
        <nav class="noprint">
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Start</a>
                </li>
                <li>
                    <a asp-controller="Tools" asp-action="Index">Tools</a>
                </li>
            </ul>
        </nav>
    </section>
</header>

<main role="main">
    @RenderBody()
</main>

<script src="~/js/htmx.min.js" asp-append-version="true"></script>
<script src="~/js/_hyperscript.min.js" asp-append-version="true"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@Html.HtmxAntiforgeryScript()
@await RenderSectionAsync("Scripts", false)
</body>
</html>

Homepage/Views/Tools/Index.cshtml
@{
    ViewBag.Title = "Tools";
    ViewBag.SubTitle = "Utitlities for everyday use";
    Layout = "_Layout";
}

<article>
    <h3>Hombank Converter</h3>
    <p>Convert Transaction History Exports from Sprakasse to a Hombank compatible CSV format</p>
    <form hx-encoding="multipart/form-data"
          hx-post
          hx-controller="Tools"
          hx-action="HomebankConvert"
          _="on htmx:afterRequest reset() me">
        <input type="file" name="file">
        <button>Convert <img height="14" class="htmx-indicator" src="/img/spinner.svg" alt="loading"/></button>
    </form>
</article>